### ISSUE TITLE
有个疑问关于i18n

### ISSUE THREAD

**Issue by lionnner** [chengww5217/one_article#1]
Hi:
IDE你用的是AndroidStudio还是 ？那个i18n的插件用的哪个呢？
我用的vscode里面也有类似的i18n插件,但是插件本身有个问题iOS模拟器总是显示英文的，试了你的是可以切换的。

**Comment by lionnner** [comment]
哦 发现了是用的AS。。。

**Comment by chengww5217** [comment]
关于 IOS 国际化固定显示英文的问题，需要看下官方这里的说明：
https://flutter.dev/docs/development/accessibility-and-localization/internationalization#appendix-updating-the-ios-app-bundle

> iOS applications define key application metadata, including supported locales, in an Info.plist file that is built into the application bundle. To configure the locales supported by your app, you’ll need to edit this file.

> First, open your project’s ios/Runner.xcworkspace Xcode workspace file then, in the Project Navigator, open the Info.plist file under the Runner project’s Runner folder.

> Next, select the Information Property List item, select Add Item from the Editor menu, then select Localizations from the pop-up menu.

> Select and expand the newly-created Localizations item then, for each locale your application supports, add a new item and select the locale you wish to add from the pop-up menu in the Value field. This list should be consistent with the languages listed in the supportedLocales parameter.

> Once all supported locales have been added, save the file.

要根据官方的提示加一下。

**Comment by chengww5217** [comment]
IDE 是 Android Studio/ IntelliJ IDEA
Plugin 是 Flutter i18n
对于 IOS 平台不显示默认语言以外的情况，优先根据上面官方的附录进行解决

**Comment by chengww5217** [comment]
简单翻译下，给所有可能出现问题的同学，有错误请指出：

附录：更新 iOS app bundle

iOS 应用程序内置的 `Info.plist` 文件，定义应用程序关键的元数据，包括支持的语言环境。要配置应用程序支持的语言环境，您需要编辑此文件。

首先，打开项目的 `ios/Runner.xcworkspace` 这个 Xcode 工作区文件（在 finder 中会自动关联 xcode 打开），然后在项目左侧导航栏（Project Navigator）中打开 `Runner` 项目的 `Runner` 文件夹下的 Info.plist 文件。

接下来，选择条目 `Information Property List`，从编辑器菜单中选择“ 添加项目（右边有一个➕图标）” ，然后从弹出菜单中选择 `Localizations`。

选择并展开新创建的 `Localizations` 项目，然后，对于应用程序支持的每个区域设置，添加新项目并从“ 值（value）”字段的弹出菜单中选择要添加的区域设置。此列表应与`supportedLocales` 参数中列出的语言一致（例如我项目中有 英文 en，中文 zh, 此处按照顺序添加即可）。

![flutter-i18n-ios](https://user-gold-cdn.xitu.io/2019/4/24/16a4e9945bd96354?w=1136&h=426&f=png&s=265182)

添加所有支持的语言环境后，保存文件。

**Comment by lionnner** [comment]
好的谢谢。
还有个疑问：
当系统语言为英文时
      localizationsDelegates: [
        S.delegate,
        // GlobalMaterialLocalizations.delegate,
        // GlobalWidgetsLocalizations.delegate
      ],
这样是没问题的，
但当更改系统语言为中文时
      localizationsDelegates: [
        S.delegate,
        // GlobalMaterialLocalizations.delegate,
        // GlobalWidgetsLocalizations.delegate
      ],
这样就有问题了。
我只想对自己写的widgets上的text进行处理难道不可以的？

**Comment by lionnner** [comment]
还有当更改系统语言为其他语言时，非英文非中文时，比如德文，日文，里面调用的是中文的？

**Comment by chengww5217** [comment]
> 当系统语言为英文时
localizationsDelegates: [
S.delegate,
// GlobalMaterialLocalizations.delegate,
// GlobalWidgetsLocalizations.delegate
],
这样是没问题的，
但当更改系统语言为中文时
localizationsDelegates: [
S.delegate,
// GlobalMaterialLocalizations.delegate,
// GlobalWidgetsLocalizations.delegate
],

不要注释这两行，
```dart
GlobalMaterialLocalizations.delegate,
GlobalWidgetsLocalizations.delegate
```

因为程序默认只能处理英语，添加上面的 delegate 才能处理默认语言外的其他语言。

> By default, Flutter only provides US English localizations. To add support for other languages, an application must specify additional MaterialApp properties, and include a separate package called flutter_localizations. As of April 2019, this package supports about 52 languages.

https://flutter.dev/docs/development/accessibility-and-localization/internationalization

**Comment by chengww5217** [comment]
> 还有当更改系统语言为其他语言时，非英文非中文时，比如德文，日文，里面调用的是中文的？

没有受支持的语言，Iphone 会从你受支持的语言列表依次读取的，实在没有了，会用默认的。

首先到设置里面看你受支持语言的优先级别：

![Simulator Screen Shot - iPhone Xʀ - 2019-04-24 at 19.25.24](https://user-gold-cdn.xitu.io/2019/4/24/16a4f19986d7eb4c?w=828&h=1792&f=png&s=155061)

如果是我这种设置方法，中文在第二个，当然显示的是中文。

如果这里没问题，那么看你设置的默认语言（第一个）是不是英文，是英语，会显示成 英文。

**Comment by lionnner** [comment]
好的，谢谢。
