### ISSUE TITLE
clone 下来运行失败

### ISSUE THREAD

**Issue by LengJunT** [chengww5217/one_article#2]
环境：AS, 安卓模拟器
报错提示：
Launching lib/main.dart on Android SDK built for x86 in debug mode...
Initializing gradle...
Resolving dependencies...
Finished with error: Please review your Gradle project setup in the android/ folder.
* Error running Gradle:
ProcessException: Process "/Users/lengjun/AndroidStudioProjects/one_article/android/gradlew" exited abnormally:

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/lengjun/AndroidStudioProjects/one_article/android/app/build.gradle' line: 54

* What went wrong:
A problem occurred evaluating project ':app'.
> path may not be null or empty string. path='null'

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 0s
  Command: /Users/lengjun/AndroidStudioProjects/one_article/android/gradlew app:properties

**Comment by chengww5217** [comment]
这个是使用 `Flutter build apk` 打包的问题。因为我 `.gradle` 设置的签名是用的自己的。你这边可以直接运行 debug 版本，或者修改  `/Users/lengjun/AndroidStudioProjects/one_article/android/app/build.gradle` 文件.

定位到 58 行，修改成如下代码，打包会使用 自带的 debug 签名进行打包。

```
buildTypes {
        release {
            signingConfig signingConfigs.debug
            minifyEnabled true
            useProguard true

            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
```

如果你也想用自己的签名打包 apk 文件，可以在 android 目录下创建 `key.properties` 文件，填入以下信息

```
storePassword=你的 store 密码
keyPassword=你的 key 密码
keyAlias=key 别名
storeFile=签名的存储路径
```
